[package]
name = "conc_testing"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "macros",
    "."
]

[dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
regex = "1"
